spring:
  auto.openurl: true
  web.loginurl: http://localhost:8080
  web.googleexcute: C:\\Users\\YSTen\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe
  datasource:
      url: jdbc:mysql://47.111.28.188:3306/test
      type: com.alibaba.druid.pool.DruidDataSource
      username: springboot
      password: springboot
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
          ddl-auto: update
    show-sql: true