spring:
  auto.openurl: true
  web.loginurl: http://localhost:8080
  datasource:
      url: jdbc:mysql://192.168.50.101/test
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: ysten123
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
          ddl-auto: update
    show-sql: true